### ISSUE TITLE
Map check needed to show area

### ISSUE THREAD

**Issue by asimard1** [syyePhenomenol/HollowKnight.MapModS#1]
When doing an Area Randomizer (Map Area or Full Area), it would be nice to have an option to show the areas discovered only if the map of the area has been acquired. As of last update, it seems a little too easy to discover areas by simply stepping into a room and directly know which items are reachable, and hiding the map behind a check would add a little more challenge, just like the "Pins over map" mode does right now. A new mode combining the "Pins over map" and "Transition" modes would be a great addition.

**Comment by asimard1** [comment]
This could also be solved by showing only the rooms that have been explored, like when doing a standard Room Randomizer.

**Comment by syyePhenomenol** [comment]
Resolved, new version contains alternative mode for area rando

**Comment by asimard1** [comment]
Thank you!
