### ISSUE TITLE
Pathfinder redundant paths

### ISSUE THREAD

**Issue by asimard1** [syyePhenomenol/HollowKnight.MapModS#11]
If two paths leading to a room are using the same transition to get to that room (for example, `roomA[left2] -> roomB` and `roomA[right1] -> roomC[left1] -> roomA[left2] -> roomB`), shouldn't the second one be removed since it doesn't add anything new to the first one?

For example, there is a room in my run for which pathfinder is recommending 8 different routes that all have the same final transition, which seems a bit useless given that these routes will have no difference between them, and some are a lot longer.

(However, when thinking about it I realize that there might be some problems when two routes have the same ending transition but you can't use one of the two depending on where you are in the room, which is impossible to know... This is more of a discussion than a bug report!)

**Comment by syyePhenomenol** [comment]
There is no reliable way to tell which starting transitions are currently reachable, so for the sake of completeness the mod gives all the possible combinations of start/final transition. I don't think there is another easy solution at the moment.

I'll close this issue for now. Feel free to ask further if you have more questions.
