### ISSUE TITLE
[MENU SELECT] not working

### ISSUE THREAD

**Issue by evnor** [syyePhenomenol/HollowKnight.MapModS#12]
I'm playing with a keyboard on the windows steam version and was unable to select a room to generate a route. I saw on fireb0rn's video that on controller this button is bound to A (jump). I tried all my keybinds, and then my whole keyboard, but none of the keys work. Resetting keybinds to default also doesn't seem to work.

**Comment by syyePhenomenol** [comment]
By default it is the Enter key. Does that work?

The room you select also must be in logic to generate a route. And check that you have benchwarp on (CTRL-B toggle).

If you have tried the above, please send a screenshot of what the map looks like, and also a ModLog (located in your Hollow Knight folder in Appdata)

**Comment by evnor** [comment]
It worked, thanks! Weird that that keybind isn't mentioned in HK options. Is it an idea to put the default keybind for various controllers in the README?

**Comment by syyePhenomenol** [comment]
I've already added the default keybinds to the README. Glad it works!
