### ISSUE TITLE
No route for certain rooms

### ISSUE THREAD

**Issue by asimard1** [syyePhenomenol/HollowKnight.MapModS#13]
Certain rooms in my run don't have any routes when I try to select them, even though I already got to them so clearly there must be a way to get there. When I check the map and look at the visited transition for that certain room (using Ctrl-U), I can find all the rooms I used to get there, however none of those rooms have any routes either. Figure out where the problem starts however is quite difficult since the rooms have branching paths and there is quite a lot of rooms...

Is there any file that could help figure out the problem? There is no error in the ModLog at all... Here is my settings file for Rando4, which might help to reproduce the problem! [settings.txt](https://github.com/syyePhenomenol/HollowKnight.MapModS/files/8694225/settings.txt) The room in question is the one with the first Hornet fight.

**Comment by asimard1** [comment]
By using Ctrl+U, I was able to find a room that was close to the hornet fight (as in not too many transitions) that actually had a route. I went there to see if it was possible to progress, and it was. When I got to the room after that one (the first room that didn't have a route), the hornet fight finally had a route and I was able to get there.

It seems as if there was a transition that I went through that wasn't being used by the route maker, so it was impossible for it to tell me to go through there even though I could. That in turn blocked a bunch of rooms from having a path. The transition in this case was Fungus3_13[Bot1] -> Waterways_08[Top1]. If I'm in Fungus3_13 (the room to the right of the stag in the vanilla map), I can't have a route to the hornet fight, but as soon as I get into Waterways_08 (the room under the bench in waterways?), I can get one!

**Comment by syyePhenomenol** [comment]
Can you send me the RawSpoiler.json file?

**Comment by asimard1** [comment]
Github tells me it doesn't support that kind of file, I'll send it to you on Discord if you don't mind!

**Comment by syyePhenomenol** [comment]
Effectively fixed for new version. I'm also going to close the other issue since it doesn't seem to happen anymore
