### ISSUE TITLE
Add dream nail for pathfinding

### ISSUE THREAD

**Issue by asimard1** [syyePhenomenol/HollowKnight.MapModS#14]
For the room White_Palace_11 (the room you get to when you dream nail the guard with awoken dream nail), there is no path to get to that room since you need to use dream nail. It would be nice if it was added. For example, I would simply put the path to get to Abyss_05 (the room where the guard is), then put "Dream nail" as the next step.

This is really not an important issue, but I was confused as to what that room was and had to use bench warp to get to the room by force to understand. A small issue that could be maybe be fixed easily for other players!

**Comment by syyePhenomenol** [comment]
I've actually already added this, but you can't see it due to the previous pathfinder problems. So it will be fixed in the next version
