### ISSUE TITLE
Shade wrong position

### ISSUE THREAD

**Issue by asimard1** [syyePhenomenol/HollowKnight.MapModS#6]
Sometimes, the shade doesn't show in the right room.

Here for example, I died in the Beast's Den, but my shade in showing in the right hub of City of Tears.

![image](https://user-images.githubusercontent.com/58919185/157350845-ae1cf959-0710-45e4-b843-44e5016f73e4.png)

**Comment by syyePhenomenol** [comment]
Does any error/exception show up in ModLog? Was the hub room connected to Beast's Den?

**Comment by asimard1** [comment]
I forgot to check the log. The hub room is not connected to Beast's Den. Beast's Den only has one exit and it goes to another room in Deepnest. If it happens again, I will check the Modlog and update.

**Comment by syyePhenomenol** [comment]
Please do! Right now I don't think I can tell what is causing the issue without ModLog and further details.
