### ISSUE TITLE
Pathfinder not shown

### ISSUE THREAD

**Issue by asimard1** [syyePhenomenol/HollowKnight.MapModS#7]
For some reason, I warped to the bench next to Bretta, and the path I need to follow doesn't show on the quick map. When I open the “Real map” or warp to another location, it is there.

![image](https://user-images.githubusercontent.com/58919185/157769540-3e7f8771-333c-49d7-9dd9-c06e8948c45c.png)

Here is the Modlog I have. It contains some errors which are related to this.

[ModLog.txt](https://github.com/syyePhenomenol/HollowKnight.MapModS/files/8227684/ModLog.txt)

Edit: Leaving fungal wastes and setting a new path brings it back.

**Comment by syyePhenomenol** [comment]
I've found the issue in the code and fixed it. Thanks for the report
